### ISSUE TITLE
get an error when run the init command

### ISSUE THREAD

**Issue by zztkm** [hatappi/gomodoro#152]
## 概要

インストール後に `gomodoro init` を実行すると以下のエラーが発生しました。

おそらく、`.gomodoro` dir が作成される前にロガーの初期化が行われているためだと思います。

```shell
gomodoro init
failed to init Logger. couldn't open sink "/Users/xxxxx/.gomodoro/gomodoro.log": open /Users/xxxxx/.gomodoro/gomodoro.log: no such file or directory
```

## 回避策

init コマンド実行前に $HOME に .gomodoro を作っておくことで、
期待する出力 `success to create config file. (/Users/xxxxx/.gomodoro/config.yaml)` が得られました。
 
```shell
mkdir ~/.gomodoro

gomodoro init
success to create config file. (/Users/xxxxx/.gomodoro/config.yaml)
```

**Comment by hatappi** [comment]
@zztkm ご報告ありがとうございます。エラーが再現したので修正しました。近日中に修正が入った最新のバージョンをリリース予定です。

**Comment by hatappi** [comment]
修正が入った v0.9.25 をリリースしました 🎉 
https://github.com/hatappi/gomodoro/releases/tag/v0.9.25

**Comment by zztkm** [comment]
@hatappi ありがとうございます！
