### ISSUE TITLE
Master is not building

### ISSUE THREAD

**Issue by masch-zz** [hatappi/gomodoro#9]
Hi!
I am trying to build master branch but I am getting the following error:

hatappi/gomodoro/libs/beep/beep.go:10:2: no buildable Go source files in /.../go/src/github.com/hatappi/gomodoro/libs/assets

There is no go files on /libs/beep. Could you add the file please?

Thanks!
masch

**Comment by hatappi** [comment]
I'm so sorry for late response.
I reworked gomodoro newly.
currenly, we can build on master branch.
